-- 01_load_synthetic_data.sql
-- Load SYNTHETIC seed data generated by generate_synthetic_data.py
--
-- Prerequisites:
--   1. alembic upgrade head
--   2. python scripts/seed.py
--   3. psql -f sql/00_prerequisites.sql
--   4. python scripts/synthetic_seed/generate_synthetic_data.py
--   5. psql -f sql/01_load_synthetic_data.sql

\echo 'Loading SYNTHETIC seed data (safe to purge later)...'

BEGIN;

-- Mark org before load
UPDATE organizations
SET settings = COALESCE(settings, '{}'::jsonb) || jsonb_build_object(
    'synthetic_data_loaded', true,
    'synthetic_data_loaded_at', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'synthetic_data_marker', 'SYNTHETIC_DATA'
)
WHERE code = 'KRISHI';

\i generated_inserts.sql

COMMIT;

\echo 'SYNTHETIC seed load complete.'
