SYSTEM_PERMISSIONS: list[tuple[str, str]] = [
    ("users:read", "View users"),
    ("users:create", "Create users"),
    ("users:update", "Update users"),
    ("users:delete", "Delete users"),
    ("roles:read", "View roles"),
    ("villages:read", "View villages"),
    ("villages:create", "Create villages"),
    ("villages:update", "Update villages"),
    ("villages:delete", "Delete villages"),
    ("crop_types:read", "View crop types"),
    ("crop_types:create", "Create crop types"),
    ("crop_types:update", "Update crop types"),
    ("crop_types:delete", "Delete crop types"),
    ("crop_prices:read", "View crop prices"),
    ("crop_prices:create", "Create crop prices"),
    ("crop_prices:update", "Update crop prices"),
    ("crop_prices:delete", "Delete crop prices"),
    ("expense_categories:read", "View expense categories"),
    ("expense_categories:create", "Create expense categories"),
    ("expense_categories:update", "Update expense categories"),
    ("expense_categories:delete", "Delete expense categories"),
    ("buyers:read", "View buyers"),
    ("buyers:create", "Create buyers"),
    ("buyers:update", "Update buyers"),
    ("buyers:delete", "Delete buyers"),
    ("agents:read", "View field agents"),
    ("agents:create", "Create field agents"),
    ("agents:update", "Update field agents"),
    ("agents:delete", "Delete field agents"),
    ("activity_types:read", "View service types"),
    ("activity_types:create", "Create service types"),
    ("activity_types:update", "Update service types"),
    ("activity_types:delete", "Delete service types"),
    ("vehicle_types:read", "View vehicle types"),
    ("vehicle_types:create", "Create vehicle types"),
    ("vehicle_types:update", "Update vehicle types"),
    ("vehicle_types:delete", "Delete vehicle types"),
    ("comments:read", "View comments"),
    ("comments:create", "Add comments"),
    ("tags:read", "View tags"),
    ("tags:create", "Add tags"),
    ("tags:delete", "Remove tags"),
    ("farmers:read", "View farmers"),
    ("farmers:create", "Create farmers"),
    ("farmers:update", "Update farmers"),
    ("farmers:delete", "Delete farmers"),
    ("documents:read", "View documents"),
    ("documents:create", "Upload documents"),
    ("documents:delete", "Delete documents"),
    ("audit:read", "View audit logs"),
    ("dashboard:read", "View dashboard"),
]

_MANAGER_MASTER = [
    "villages:read",
    "villages:create",
    "villages:update",
    "crop_types:read",
    "crop_types:create",
    "crop_types:update",
    "crop_prices:read",
    "crop_prices:create",
    "crop_prices:update",
    "expense_categories:read",
    "expense_categories:create",
    "expense_categories:update",
    "buyers:read",
    "buyers:create",
    "buyers:update",
    "agents:read",
    "agents:create",
    "agents:update",
    "activity_types:read",
    "activity_types:create",
    "activity_types:update",
    "vehicle_types:read",
    "vehicle_types:create",
    "vehicle_types:update",
    "farmers:read",
    "farmers:create",
    "farmers:update",
    "comments:read",
    "comments:create",
    "tags:read",
    "tags:create",
]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "OWNER": [code for code, _ in SYSTEM_PERMISSIONS],
    "MANAGER": [
        "users:read",
        "users:update",
        "roles:read",
        *_MANAGER_MASTER,
        "documents:read",
        "documents:create",
        "audit:read",
        "dashboard:read",
    ],
    "SUPERVISOR": [
        "villages:read",
        "crop_types:read",
        "crop_prices:read",
        "buyers:read",
        "agents:read",
        "activity_types:read",
        "vehicle_types:read",
        "farmers:read",
        "farmers:create",
        "farmers:update",
        "comments:read",
        "comments:create",
        "tags:read",
        "documents:read",
        "documents:create",
        "dashboard:read",
    ],
    "AGENT": [
        "comments:read",
        "comments:create",
        "tags:read",
        "dashboard:read",
    ],
    "DRIVER": [
        "vehicle_types:read",
        "comments:read",
        "comments:create",
        "tags:read",
        "dashboard:read",
    ],
    "WORKER": [
        "comments:read",
        "comments:create",
        "documents:read",
        "documents:create",
    ],
}

ROLE_DEFINITIONS: list[tuple[str, str]] = [
    ("OWNER", "Owner"),
    ("MANAGER", "Manager"),
    ("SUPERVISOR", "Farm Supervisor"),
    ("AGENT", "Field Agent"),
    ("DRIVER", "Driver"),
    ("WORKER", "Worker"),
]
